### ISSUE TITLE
Move Logger projects from Akka.NET organization

### ISSUE THREAD

**Issue by alexvaluyskiy** [AkkaNetContrib/Home#2]
- [x] Akka.Logger.log4net (possible maintainers: @Danthar or @Horusiath)
- [x] Akka.Logger.slf4net (possible maintainers: @Danthar)
- [x] Akka.Logger.CommonLogging (possible maintainers: @Danthar)

**Comment by Danthar** [comment]
Sure, ill take those.

**Comment by alexvaluyskiy** [comment]
@Danthar All that packages will be supported by Akka.NET core developers from the beginning. But if we find someone outside, who is using some project in production, and he is ready to maintain the package, it would be good to transfer the ownership to him
